---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE, warning=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)

library(p8105.datasets)
data("rest_inspec")
```

We focus on restaurants located in The Bronx borough without NAs in score and grade, and use some variables to create plots. 

```{r}
rest_inspec = 
  rest_inspec |>
  janitor::clean_names() |>
  filter(!is.na(grade),
         !is.na(score),
         boro == "BRONX",
         cuisine_description %in% c("Italian", "Mexican", "African", "Spanish", "American", "Japanese", "French")) |>
  select(boro, dba, cuisine_description, street, building, score, grade)
```



Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r, warning=FALSE}
rest_inspec |>
  mutate(text_label = str_c("dba:",dba,
                            "\nCuisine:", cuisine_description,
                            "\nScore:", score)) |>
  plot_ly(x = ~street, y = ~building, color = ~street,
          type = "scatter", mode = "markers", text = ~text_label, alpha = 0.5)
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_inspec |> 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) |> 
  plot_ly(y = ~score, color = ~cuisine_description, 
          type = "box", colors = "viridis")
```

### Chart C 

```{r}
rest_inspec |>
  filter(grade != "Not Yet Graded") |>
  group_by(cuisine_description) |>
  count(grade) |>
  plot_ly(x = ~cuisine_description, y = ~n, color = ~grade, 
          type = "bar", colors = "viridis")
```









